name: Java CI

on:
  push:
    branches:
      - main
      - master
  pull_request:
    branches:
      - main
      - master

jobs:
  build:
    runs-on: ubuntu-latest  

    steps:
   
    - name: Checkout repository
      uses: actions/checkout@v3

   
    - name: Set up JDK
      uses: actions/setup-java@v3
      with:
        java-version: '11'  

    
    - name: Compile Java Code
      run: |
        mkdir -p out
        javac -d out -cp ".:src/main/java:src/test/java" $(find src/main/java src/test/java -name "*.java")

    
    - name: Run Unit Tests
      run: |
        java -cp "out:src/main/java:src/test/java" org.junit.runner.JUnitCore test.LoginAppTest
