name: Java CI

on:
  push:
    branches:
      - main
      - master
  pull_request:
    branches:
      - main
      - master

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout repository
      - name: Checkout repository
        uses: actions/checkout@v3

      # Step 2: Set up JDK
      - name: Set up JDK
        uses: actions/setup-java@v3
        with:
          java-version: '11'
          distribution: 'temurin'

      # Step 3: Download Dependencies
      - name: Download Dependencies
        run: |
          mkdir -p lib
          curl -L -o lib/junit-4.13.2.jar https://repo1.maven.org/maven2/junit/junit/4.13.2/junit-4.13.2.jar
          curl -L -o lib/hamcrest-core-1.3.jar https://repo1.maven.org/maven2/org/hamcrest/hamcrest-core/1.3/hamcrest-core-1.3.jar
          curl -L -o lib/mysql-connector-j-8.0.30.jar https://repo1.maven.org/maven2/mysql/mysql-connector-java/8.0.30/mysql-connector-java-8.0.30.jar

      # Step 4: Wait for Database Connection
      - name: Verify Database Connectivity
        run: |
          for i in {1..10}; do
            if mysqladmin ping -h 127.0.0.1 -uroot -pMahi_123 --silent; then
              echo "Database is up!"
              break
            fi
            echo "Waiting for database connection..."
            sleep 5
          done

      # Step 5: Compile Java Code
      - name: Compile Java Code
        run: |
          mkdir -p out  
          javac -d out -cp ".:lib/*" \
            "Assignment 2/src/main/java/main/LoginService.java" \
            "Assignment 2/src/main/java/main/LoginApp.java" \
            "Assignment 2/src/test/java/test/LoginAppTest.java"

      # Step 6: Run Unit Tests
      - name: Run Unit Tests
        run: |
          java -Djava.awt.headless=true -cp "out:lib/*" org.junit.runner.JUnitCore test.LoginAppTest
