name: Java CI

on:
  push:
    branches:
      - main
      - master
  pull_request:
    branches:
      - main
      - master

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: List Repository Files
        run: ls -R

      - name: Set up JDK
        uses: actions/setup-java@v3
        with:
          java-version: '11'
          distribution: 'temurin'

      - name: Compile Java Code
        run: |
          mkdir -p out  
          javac -d out -cp ".:Assignment 2/src/main:Assignment 2/src/test" \
            "Assignment 2/src/main/java/main/LoginApp.java" \
            "Assignment 2/src/test/java/test/LoginAppTest.java"

      - name: Run Unit Tests
        run: |
          java -cp "out:Assignment 2/src/main:Assignment 2/src/test" \
            org.junit.runner.JUnitCore test.LoginAppTest
